# Generated by Django 3.2.6 on 2022-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=400)),
            ],
        ),
    ]
