# Generated by Django 3.2.6 on 2022-01-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20220115_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='first_name',
            new_name='username',
        ),
    ]
