# Generated by Django 3.2.6 on 2022-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_first_name_accounts_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='password',
            new_name='District',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
        migrations.AddField(
            model_name='accounts',
            name='Description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
