# Generated by Django 3.2.6 on 2022-01-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20220117_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='Bedrooms',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts',
            name='Price',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
